spring.datasource.url=jdbc:postgresql://localhost:5432/petUfal
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret=uma-chave-bem-grande-com-pelo-menos-32-caracteres
jwt.issuer=api-animais
jwt.expiration-hours=2